# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmeZpJvjGs7IjLZgrgbaegJ94Fas05dz
"""

import zipfile
from io import BytesIO

app_py = """
# (Paste the entire app.py code here)
"""

requirements_txt = """
streamlit
pandas
numpy
matplotlib
seaborn
scikit-learn
"""

buffer = BytesIO()
with zipfile.ZipFile(buffer, 'w') as z:
    z.writestr("app.py", app_py.strip())
    z.writestr("requirements.txt", requirements_txt.strip())

buffer.seek(0)

with open("streamlit_gaming_dashboard.zip", "wb") as f:
    f.write(buffer.read())

print("ZIP file created! You can download it now from the Files section.")